import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* mx auto margin left margin right auto */}
      <div className="max-w-3xl mx-auto p-4">
        <Navbar/>

        {/* children is component in current page */}
        <div className = "mt-8">{children}</div>
      </div>
    </html>
  )
}
